#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#

# Attempt to set APP_HOME
PRG="$0"
while [ -h "$PRG" ]; do
    ls=$(ls -ld "$PRG")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(dirname "$PRG")/"$link"
    fi
done
SAVED="$(pwd)"
cd "$(dirname "$PRG")/" >/dev/null
APP_HOME="$(pwd -P)"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

OS_NAME=$(uname -s)
case "$OS_NAME" in
    CYGWIN* | MSYS* | MINGW*)
        IS_WINDOWS=true
        ;;
    *)
        IS_WINDOWS=false
        ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ]; then
    echo "Error: gradle-wrapper.jar not found at $CLASSPATH"
    echo "Run './gradlew wrapper' to generate it, or download from:"
    echo "  https://github.com/gradle/gradle-distributions/releases/download/v8.5.0/gradle-8.5-bin.zip"
    echo "  (extract lib/gradle-wrapper-8.5.jar as gradle/wrapper/gradle-wrapper.jar)"
    exit 1
fi

if [ -n "$JAVA_HOME" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

if [ ! -x "$JAVACMD" ] && [ "$IS_WINDOWS" = "true" ]; then
    JAVACMD="java.exe"
fi

if [ ! -x "$(command -v "$JAVACMD")" ]; then
    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

GRADLE_OPTS="${GRADLE_OPTS} -Dorg.gradle.appname=${APP_BASE_NAME}"

exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
